
name: Pull Request Milestone

on:
  workflow_dispatch:

jobs:
  milestone:
    name: Generate and Publish Milestone Document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Milestone Documentation Generator
        uses: ory/milestone-action@v0.0.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Commit and push milestone changes
        run: |
          git add -A
          (git commit -a -m "autogen(docs): update milestone" && git push) || exit 0
